name: Build, Test & Package

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'docs/**' # Don't run workflow when files are only in the /docs directory

jobs:
  build:
    runs-on: windows-2019
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: .NET Build
      run: dotnet build Build.csproj -c Release /p:CI=true
    - name: .NET Test
      run: dotnet test Build.csproj -c Release --no-build /p:CI=true
    - name: .NET Pack
      run: dotnet pack Build.csproj --no-build -c Release /p:PackageOutputPath=${env:GITHUB_WORKSPACE}\.nupkgs /p:CI=true
    - name: Push to MyGet
      run: dotnet nuget push ${env:GITHUB_WORKSPACE}\.nupkgs\*.nupkg -s https://www.myget.org/F/stackoverflow/api/v2/package -k ${{ secrets.MYGET_API_KEY }}
