name: Package Build CI

on:
  pull_request:
  push:
    branches:
    - master
    paths:
    - '*'
    - '!/docs/*' # Don't run workflow when files are only in the /docs directory

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: .NET Build
      run: dotnet build Build.csproj -c Release /p:CI=true
    - name: .NET Test
      run: dotnet test Build.csproj -c Release --no-build /p:CI=true
    - name: .NET Lib Pack
      run: dotnet pack Build.csproj --no-build -c Release /p:PackageOutputPath=%CD%\.nupkgs /p:CI=true
